version: '2'

services:

    elasticsearch:
        #mem_limit: 1024m
        build:
            context: ./elasticsearch
            args:
                ELK_VERSION: $ELK_VERSION
        container_name: elk_c_es
        image: elk_i_es:1.0.0
        volumes:
            - ./datas/elasticsearch:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        networks:
            #- default
            - backend

    elasticsearch2:
        #mem_limit: 1024m
        build:
            context: ./elasticsearch
            args:
                ELK_VERSION: $ELK_VERSION
        container_name: elk_c_es2
        image: elk_i_es2:1.0.0
        volumes:
            - ./datas/elasticsearch2:/usr/share/elasticsearch/data
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - "discovery.zen.ping.unicast.hosts=elasticsearch"
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        networks:
            #- default
            - backend
        depends_on:
            - elasticsearch

    logstash:
        #mem_limit: 2048m
        build:
            context: ./logstash
            args:
                ELK_VERSION: $ELK_VERSION
        container_name: elk_c_logstash
        image: elk_i_logstash:1.0.0
        volumes:
            - ./datas/nginx:/var/log/nginx
        external_links:
            - elasticsearch
        ports:
            - 5044:5044
        environment:
            - "LS_JAVA_OPTS=-Xms512m -Xmx512m"
        networks:
            #- default
            - backend
        depends_on:
            - elasticsearch

    kibana:
        #mem_limit: 512m
        build:
            context: ./kibana
            args:
                ELK_VERSION: $ELK_VERSION
        container_name: elk_c_kibana
        image: elk_i_kibana:1.0.0
        external_links:
            - elasticsearch
        ports:
            - 5601:5601
        networks:
            #- default
            - backend
        depends_on:
            - elasticsearch

    filebeat:
        #mem_limit: 1024m
        build:
            context: ./filebeat
            args:
                ELK_VERSION: $ELK_VERSION
        container_name: elk_c_filebeat
        image: elk_i_filebeat:1.0.0
        volumes:
            - ./datas/nginx:/var/log/nginx/
        external_links:
            - logstash
        networks:
            #- default
            - backend

    nginx:
        #mem_limit: 64m
        build: ./nginx
        container_name: elk_c_nginx
        image: elk_i_nginx:1.0.0
        ports:
            - "80:80"
        volumes:
            - ./datas/nginx:/var/log/nginx
            - ./html:/var/www/html
        networks:
            #- default
            - backend

networks:
    #frontend:
    #    driver: bridge
    backend:
        driver: bridge
