filebeat:
  prospectors:
    - input_type: log
      paths:
        - /var/log/nginx/default_access.log
      tags: ["elk-nginx-access"]

    - input_type: log
      paths:
        - /var/log/nginx/default_error.log
      tags: ["elk-nginx-error"]

output:
  logstash:
    hosts: ["logstash:5044"]
    #hosts: ["52.221.216.84:5044"]
    #hosts: ["xxx.com:5044"]
